package com.hungteen.pvz.generator.loot;

import com.hungteen.pvz.common.event.RegisterSproutsEvent;
import com.hungteen.pvz.common.item.SeedItem;
import com.hungteen.pvz.common.item.SeedPacketItem;
import com.hungteen.pvz.common.register.PVZEntities;
import com.hungteen.pvz.common.register.PVZItems;
import com.hungteen.pvz.generator.InvasionTypeGen;
import com.hungteen.pvz.util.Util;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.EnchantRandomlyFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.function.BiConsumer;
import java.util.function.Consumer;

public class TreasureLootGen implements Consumer<BiConsumer<ResourceLocation, LootTable.Builder>> {
    @Override
    public void accept(BiConsumer<ResourceLocation, LootTable.Builder> build) {
        InvasionTypeGen.loots.forEach(build);
        build.accept(Util.prefix("chests/zombie_structure/snowman"), LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.SNOW_PEA.get())).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.ICEBERG_LETTUCE.get())).setWeight(3)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.SNOW_PEA.get())).setWeight(6)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.ICEBERG_LETTUCE.get())).setWeight(2)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(PVZItems.SPROUT.get()).setWeight(12)
                                .apply(RegisterSproutsEvent.SetSproutTypeFunction.Builder.of("sprout.pvz.icy")))
                        .add(LootItem.lootTableItem(PVZItems.MARIGOLD_SPROUT.get()).setWeight(8))
                        .add(LootItem.lootTableItem(Items.BOOK).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment())))
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0F, 5.0F))
                        .add(LootItem.lootTableItem(Items.REDSTONE).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(Items.LAPIS_LAZULI).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.ORIGIN_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.GELUM_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CONE_HELMET.get()).setWeight(5))
                        .add(LootItem.lootTableItem(Items.DIAMOND).setWeight(1)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F))))
                        .add(LootItem.lootTableItem(Items.EMERALD).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 4.0F))))
                        .add(LootItem.lootTableItem(Items.CHARCOAL).setWeight(8)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F))))
                        .add(LootItem.lootTableItem(Items.BREAD).setWeight(8)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CABBAGE_SEED.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CORN.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))))
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(2.0F))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH).setWeight(10))
                        .add(LootItem.lootTableItem(Items.BONE).setWeight(10))
                        .add(LootItem.lootTableItem(Items.WHEAT).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 3.0F))))
                )
        );
        build.accept(Util.prefix("chests/zombie_structure/bucket"), LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.SPLIT_PEA.get())).setWeight(2)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.SPLIT_PEA.get())).setWeight(6)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(PVZItems.SPROUT.get()).setWeight(12)
                                .apply(RegisterSproutsEvent.SetSproutTypeFunction.Builder.of("sprout.pvz.common")))
                        .add(LootItem.lootTableItem(PVZItems.MARIGOLD_SPROUT.get()).setWeight(6))
                        .add(LootItem.lootTableItem(Items.BOOK).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment())))
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0F, 5.0F))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(6.0F, 18.0F))))
                        .add(LootItem.lootTableItem(Items.GOLD_INGOT).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.ORIGIN_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(Items.GUNPOWDER).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.BUCKET_HELMET.get()).setWeight(2))
                        .add(LootItem.lootTableItem(Items.DIAMOND).setWeight(1)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F))))
                        .add(LootItem.lootTableItem(Items.COAL).setWeight(8)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CABBAGE_SEED.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CORN.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))))
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(2.0F))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH).setWeight(5))
                        .add(LootItem.lootTableItem(Items.BONE).setWeight(10))
                        .add(LootItem.lootTableItem(Items.GUNPOWDER).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F))))
                        .add(LootItem.lootTableItem(Items.WHEAT).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 3.0F))))
                )
        );
        build.accept(Util.prefix("chests/zombie_structure/duck"), LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.LILY_PAD.get())).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.LILY_PAD.get())).setWeight(3)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.TANGLE_KELP.get())).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.TANGLE_KELP.get())).setWeight(3)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(PVZItems.SPROUT.get()).setWeight(12)
                                .apply(RegisterSproutsEvent.SetSproutTypeFunction.Builder.of("sprout.pvz.water")))
                        .add(LootItem.lootTableItem(PVZItems.MARIGOLD_SPROUT.get()).setWeight(8))
                        .add(LootItem.lootTableItem(Items.BOOK).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment())))
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0F, 5.0F))
                        .add(LootItem.lootTableItem(Items.PRISMARINE_CRYSTALS).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F))))
                        .add(LootItem.lootTableItem(Items.PRISMARINE_SHARD).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F))))
                        .add(LootItem.lootTableItem(PVZItems.ORIGIN_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.AQUA_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F))))
                        .add(LootItem.lootTableItem(PVZItems.DUCK_LIFEBUOY.get()).setWeight(2))
                        .add(LootItem.lootTableItem(Items.DIAMOND).setWeight(1)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F))))
                        .add(LootItem.lootTableItem(Items.EMERALD).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 4.0F))))
                        .add(LootItem.lootTableItem(Items.BUCKET).setWeight(8))
                        .add(LootItem.lootTableItem(PVZItems.CABBAGE_SEED.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CORN.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))))
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(2.0F))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH).setWeight(5))
                        .add(LootItem.lootTableItem(Items.BONE).setWeight(10))
                        .add(LootItem.lootTableItem(Items.PUFFERFISH).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F))))
                        .add(LootItem.lootTableItem(Items.COD).setWeight(10))
                )
        );
        build.accept(Util.prefix("chests/zombie_structure/cemetery"), LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
                        .add(LootItem.lootTableItem(SeedPacketItem.getSeedPacket(PVZEntities.VELOCI_RADISH.get())).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(SeedItem.getSeed(PVZEntities.VELOCI_RADISH.get())).setWeight(8)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2f, 8f))))
                        .add(LootItem.lootTableItem(PVZItems.SPROUT.get()).setWeight(12)
                                .apply(RegisterSproutsEvent.SetSproutTypeFunction.Builder.of("sprout.pvz.common")))
                        .add(LootItem.lootTableItem(PVZItems.MARIGOLD_SPROUT.get()).setWeight(6))
                        .add(LootItem.lootTableItem(Items.BOOK).setWeight(1)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment()))
                        .add(LootItem.lootTableItem(PVZItems.ANVIL_HAMMER.get()).setWeight(4)
                                .apply(EnchantRandomlyFunction.randomApplicableEnchantment())))
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0F, 5.0F))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(6.0F, 18.0F))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(6.0F, 18.0F))))
                        .add(LootItem.lootTableItem(Items.IRON_INGOT).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.ORIGIN_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(4.0F, 9.0F))))
                        .add(LootItem.lootTableItem(PVZItems.TERRA_ESSENCE.get()).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 5.0F))))
                        .add(LootItem.lootTableItem(Items.CANDLE).setWeight(4)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 8.0F))))
                        .add(LootItem.lootTableItem(Items.ANVIL).setWeight(3))
                        .add(LootItem.lootTableItem(Items.DIAMOND).setWeight(1)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F))))
                        .add(LootItem.lootTableItem(Items.EMERALD).setWeight(6)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(3.0F, 8.0F))))
                        .add(LootItem.lootTableItem(PVZItems.CORN.get()).setWeight(10)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 4.0F)))))
                .withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(2.0F))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH).setWeight(10))
                        .add(LootItem.lootTableItem(Items.BONE).setWeight(10))
                        .add(LootItem.lootTableItem(Items.WHEAT).setWeight(5)
                                .apply(SetItemCountFunction.setCount(UniformGenerator.between(2.0F, 3.0F))))
                )
        );
    }
}
